name: CI/CD for Nexus ui

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker-compose build
          docker tag nexus-ui:latest ${{ secrets.DOCKER_USERNAME }}/nexus-ui:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nexus-ui:latest

  deploy:
    name: Deploy Nexus ui to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/nexus-ui:latest

            echo "Creating docker-compose.yml for deployment..."
            cat << 'COMPOSE_FILE' > docker-compose.yml
            version: '3.8'

            services:
              nexus-ui:
                image: ${{ secrets.DOCKER_USERNAME }}/nexus-ui:latest
                ports:
                  - "4173:4173"
                environment:
                  - NODE_ENV=production
            COMPOSE_FILE

            echo "Starting containers with Docker Compose..."
            docker-compose up -d

            echo "Deployment successful!"
          EOF
